### ISSUE TITLE
Add retry_if_exception_match

### ISSUE THREAD

**Issue by PhML** [jd/tenacity#125]
As there is `retry_if_exception_type`, would it be possible to have `retry_if_exception_match`?
It would replace :
```python
retry_if_exception(lambda e: re.match(pattern, str(e)))
```
by:
```python
retry_if_exception_match(pattern)
```

**Comment by immerrr** [comment]
It could be nicer to extend the existing `retry_if_exception` to accept `match` kwarg, like [pytest.raises does](https://docs.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions):
```
retry_if_exception(MyException, match='zzz')
retry_if_exception(MyException, match=some_precompiled_regexp)
```

**Comment by Brian-Williams** [comment]
I think having a separate classes is a good idea because it gives greater granularity for use cases where several retry predicates need to be chained.

It allows you to do things like separating exception type from exception message.

`retry=(retry_if_exception_type=MyException1 | retry_if_exception_message(match=r'a[bc]*'))`

Then even if exception `MyException2` raises with errormessage 'ab' it will retry.

@jd Any interest in this? I put together a rough sketch of what it could look like [here](https://github.com/Brian-Williams/tenacity/commit/8d19588434e0ea90bb83f56615153adba617c9ea).

**Comment by jd** [comment]
@Brian-Williams That sounds like a good idea. Feel free to send a PR.

**Comment by jamesbraza** [comment]
Should this issue be closed? I think it was resolved
