### ISSUE TITLE
`wait_random_exponential(min)`: unexpected behavior 

### ISSUE THREAD

**Issue by thomas-riccardi** [jd/tenacity#162]
Since #135 `wait_exponential()` accepts a `min` parameter: the wait will *never* be lower than `min`.

However, `wait_exponential()` is the base class of `wait_random_exponential()`, and this results in an unexpected semantic for `min` for `wait_random_exponential()`:
I would have expected that it would *also* mean here that the wait *never* be lower than `min`.
But it's not the case: the `min` capping is only done in `wait_exponential()`: the random is still applied on the range `[0, parent]`.

I would thus expect that `wait_random_exponential(min)` does a random on the range `[min, parent(min=0)]` (which is in fact the same as the simpler to implement `[min, parent]`).

Or maybe we need 2 `min`: the parent min to compute the random upper bound, and a new min for the random lower bound ? It would avoid having the same value `min` multiple times until the exponential exceeds it.

**Comment by jd** [comment]
If you read through the docstring and source https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/, you'll see that `wait_random_exponential` is equivalent to the `Full Jitter` implementation.

What you want is different and more like `Equal Jitter`, where some of the backoff delay is always added — not starting at `0` for the random range but at `cap/2`.

The quoted source (AWS blog) indicates that the best method is `Full Jitter` so that's why it's the only one implemented. You could implement your own strategy, though. :)

**Comment by thomas-riccardi** [comment]
@jd OK, I initially opened this issue as the semantic of `min` was not clear (`max` does have the same semantic for both `wait_exponential` and `wait_random_exponential`, and `min` does not), which was initially surprising.
But indeed the source code is easily readable and the `Full Jitter` seems to be the best algo anyway.
I'll close the issue.
