### ISSUE TITLE
After callback only invoked by failed attempt?

### ISSUE THREAD

**Issue by occoder** [jd/tenacity#237]
The doc says:

> It's possible to execute an action before any attempt of calling the function by using the before callback function:
> In the same spirit, It's possible to execute after a call that failed:

But in fact, they are not in the same spirit.
The "before" callback is invoked unconditionally whereas "after" callback is only invoked in case current attempt fails.
I'm wondering what is the real counterpart to the "before" callback?

**Comment by jd** [comment]
It seems pretty easy to call some code after a function succeeded since… it's the code after the retried function call that is executed. I'm not really sure what you want to achieve?

**Comment by occoder** [comment]
> It seems pretty easy to call some code after a function succeeded since… it's the code after the retried function call that is executed. I'm not really sure what you want to achieve?

Yes, I do agree your point. But, IMHO, the symmetrical arrangement that the "after" callback matches the "before" callback makes the code easier to follow. After all, after_log function is not necessarily only logging the failed case.

**Comment by jd** [comment]
Alright, but is there something in particular that you want to achieve and that you can't do right now?

**Comment by occoder** [comment]
> Alright, but is there something in particular that you want to achieve and that you can't do right now?

Nope. Still I'd like to make the decorator and its associated callback less invasive to my business logic. I'm really reluctant to drag the "after" callback from within the decorator. :-(

**Comment by Gaasmann** [comment]
@jd I may have a use case for that. We use a class calling a flaky external service in a lot of places so we made a wrapper for it where tenacity is called to do its magic. The wrapper logs all attempts and results with structured logs so we can debug and make stats if needed. We use the RetryCallState to get a lot of info about how many attempts we did, how long it took since the first call, the outcome and so on. Being able to call an after callback when successful would allow us to have this info in our log with the same format than the rest with all the info RetryCallState provides. Right now I only see the attempts but no confirmation if the call actually succeeded or if the program just crashed :-)
