### ISSUE TITLE
Fail if a certain number of attempts is made per time unit.

### ISSUE THREAD

**Issue by mezhaka** [jd/tenacity#301]
I have a function that connects over the wire and is expected to fail once in a while, however if it is not able to connect for some time T, I'd like it to fail.
Consider:
```python
@tenacity.retry(
    retry=if_less_failures_within_timespan(TimeOutError, allowed_failures=10, timespan_seconds=120),  # <- this is what I want
    wait=tenacity.wait_exponential(),
)
def pseudo():
    connection = connect_to_server()
    send_stuff(connection)
```
The `send_stuff` can fail if the connection is broken.  In this case I to retry. If N retries in a row fail during time span T, I'd like to raise (this is clear how to do), but if no error occurred during time span T, I'd like to reset the error counter.

Is there a way to do that out of the box?  If not, can someone suggest a tenacity way of implementing it (

**Comment by mezhaka** [comment]
I came up with something like this:

```python
class retry_unless_more_than_n_fails_in_time_span:
    def __init__(self, n: int, span_seconds: float):
        self._span_seconds = span_seconds
        self._n = n
        self._failure_time_stamps_seconds = collections.deque()
        self._deleteme = []

    def __call__(self, retry_state: tenacity.RetryCallState):
        if not retry_state.outcome.failed:
            return False

        now = time.monotonic()
        self._failure_time_stamps_seconds.append(now)

        # Accumulate at least self._n failures.
        if len(self._failure_time_stamps_seconds) <= self._n:
            return True

        oldest_failure_timestamp = self._failure_time_stamps_seconds.popleft()
        self._deleteme.append(now - oldest_failure_timestamp)
        if now - oldest_failure_timestamp < self._span_seconds:
            # self._n errors occured during span_seconds happened -- stop retrying
            return False
        return True

class FailOnSchedule:
    """Raise TestRetryError after waiting.

    For example, o = FailOnSchedule([0.1, 0.2]), calling o() would sleep 0.1 seconds, then
    raise, calling it again would wait for 0.2 seconds and then raise, calling it third time
    would raise without waiting.
    """

    class TestRetryError(Exception):
        pass

    def __init__(self, wait_before_fail: List[float]):
        self.wait_before_fail = list(reversed(wait_before_fail))

    def __call__(self):
        if self.wait_before_fail:
            time.sleep(self.wait_before_fail.pop())
        raise FailOnSchedule.TestRetryError


def test_retry():
    # Generates 4 failures.
    fail_on_schedule = FailOnSchedule([0.01, 0.01, 0.01, 0.001])

    # Tolerates at most 2 failures within 0.02 seconds, so the above schedule combined with
    # retry_strategy below should fail on the very last attempt because there would be 2 errors in the time span of
    # ~ 0.011 seconds.
    retry_strategy = kubernetes.retry_unless_more_than_n_fails_in_time_span(n=2, span_seconds=0.02)

    fail_on_schedule = tenacity.retry(retry=retry_strategy, reraise=True)(fail_on_schedule)
    with pytest.raises(FailOnSchedule.TestRetryError):
        fail_on_schedule()
    assert fail_on_schedule.wait_before_fail == []
    assert fail_on_schedule.retry.statistics["attempt_number"] == 4


def test_no_retry_on_success():
    retry_strategy = kubernetes.retry_unless_more_than_n_fails_in_time_span(n=2, span_seconds=0.02)

    @tenacity.retry(retry=retry_strategy, reraise=True)
    def i_am_ok():
        return True

    assert i_am_ok()
    assert i_am_ok.retry.statistics["attempt_number"] == 1
```

What I don't like is that it's not orthogonal to other retry parameters, like "wait".  Now one needs to compute the wait time to be compatible with the `n` and `span_seconds`.

**Comment by asqui** [comment]
@mezhaka I've been meaning to reply to this and have been thinking about your implementation.

I think it's a nice pattern and I like your implementation, but I've been thinking about what you said regarding coupling to the wait parameter... The two are inevitably tied, because wait delay limits your rate of attempts, which limits your maximal rate of failures, so it's possible that your maximal rate of failures is limited to a lower level than the `retry_unless_more_than_n_fails_in_time_span` constraint, making it useless.

But this got me to wondering: Is there a reason why simply setting max attempts / max duration won't let you achieve what you want?

The retry state is reset every time you call your method, so all the retry parameters apply to a single call of the wrapped method.

Taking your specific example, one call of `pseudo()` will establish a connection and send one batch of 'stuff' over it. If `send_stuff()` fails, then tenacity gets involved to retry the operation, but if it does not fail, then `pseudo()` succeeds, and tenacity has nothing to do.

Does this window-based failure monitoring apply at a higher level in your real application? Or does `pseudo()` have a loop inside where it is calling `send_stuff()` repeatedly while pulling from a work-queue?
