### ISSUE TITLE
how to combine  retry_if_not_exception_type conditions

### ISSUE THREAD

**Issue by broven** [jd/tenacity#449]
```python
from tenacity import (
    retry,
    retry_if_not_exception_type,
)
class Error1(Exception):
    pass
class Error2(Exception):
    pass
@retry(
    retry=(retry_if_not_exception_type(Error1) | retry_if_not_exception_type(Error2))
)
def not_expected():
    print("retry")
    raise Error1()
not_expected()

```

I'm trying combine multple `retry_if_not_exception_type`, but it seem's not work as expected, function keep retry

**Comment by jd** [comment]
Hi @broven 

Let's read your code: you raise `Error1` and you wrote it should retry if one of those is true, due to the `|` or operator:
1. `retry_if_not_exception_type(Error1)` is true
2. `retry_if_not_exception_type(Error2)` is true

Alright, indeed condition 1 is false. Let's try condition 2 then. It's true: `Error1` is not type `Error2`.

So it retries.
