### ISSUE TITLE
add to docs how to retrieve the actual function Exception

### ISSUE THREAD

**Issue by asafcombo** [jd/tenacity#56]
example:
```
@retry(stop=stop_after_attempt(1))
def divisionByZero():
   print 1/0

try:
    divisionByZero
except:
    except Exception as e: 
        print e.last_attempt.exception()
       ### or  e.reraise
```

Also would be nice if it could be added a functionality that catches the last exception so We won't have to add try/except controls. What I mean is:

```
@retry(onFiinalException=userFunction)

def userFunction(Exception):
   #gets the final exception and does something 
   logger.error(Exception)
    logger.error(e.reraise)
```

**Comment by jd** [comment]
So this basically means changing:

```python
@retry(stop=stop_after_attempt(1))
def divisionByZero():
   print 1/0

try:
    divisionByZero()
except:
    logger.error("Something bad happened")
```

to

```python
def userFunction(e):
    logger.error("Something bad happened")

@retry(stop=stop_after_attempt(1), final=userFunction)
def divisionByZero():
   print 1/0

divisionByZero()
```

It's not really faster to type or anything. What it does is that it actually hardcode the error management in the decorator for all future calls. So that'd basically be something like:

```python
@retry(stop=stop_after_attempt(1))
def divisionByZero():
   print 1/0

def divide_by_zero():
    try:
        divisionByZero()
    except:
        logger.error("Something bad happened")

divide_by_zero()
```

To make sure the error handling is consistent across several calls. I think that the use of the `after` keyword argument to specify a behavior when something fails between retries is a better choice to have things such as logging tied to the retrying action be made. Doing things way before or way after retries should not lie to tenacity, it's up to each application to build its workflow around it.
